version: "3"
services:
  app:
    build: .
    container_name: app
    ports:
      - 8090:8090
    restart: always
    depends_on:
      - mq
      - db
  mq:
    image: rabbitmq:alpine
    container_name: mq
    ports:
      - 5672:5672
      - 15672:15672
  db:
    image: postgres:alpine
    container_name: db
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
volumes:
  pgdata:
