spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  datasource:
    driverClassName: org.h2.Driver
    username: ${DB_USER}
    password: ${DB_PASS}
    url: ${DB_URL}
  h2.console:
    enabled: true
    path: /h2
    settings:
      trace: false
      web-allow-others: false

