server:
  port: ${config.port}

spring:
  profiles:
    active: 'local'
  application:
    name: fipe-price-checker
  datasource:
    username: ${config.db.user}
    password: ${config.db.password}
    url: ${config.db.url}
flyway:
  url: ${config.db.url}
  user: ${config.db.user}
  password: ${config.db.password}
